Update the tuned profile to set higher scheduler priority
openshift-kni/performance-addon-operators pull request #462
Opened 2020-12-08 13:56 UTC by cynepco3hahue

The stalld service has higher priority than `ksoftirqd`, `rcub` and `rcuc` that
can lead to the system freeze under the load pressure. To avoid it we should
raise the scheduler priority of these threads to be higher than the stalld service.

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

2020-12-08 13:57 UTC, cynepco3hahue commented
/bugzilla refresh

2020-12-12 18:24 UTC, yanirq requested changes
Added comments per rt-kernel team feedback on a different thread

2020-12-12 18:24 UTC, yanirq commented on build/assets/tuned/openshift-node-performance
> +group.rcuc=0:f:13:*:rcuc.*
ksoftirqd and rcuc should run with the same rt priority (11)

2020-12-14 11:09 UTC, cynepco3hahue commented
@yanirq Thanks for the answer, I updated the PR

2020-12-15 08:52 UTC, fromanirh commented
/retest

2020-12-15 10:33 UTC, fromanirh commented
/retest

2020-12-16 17:49 UTC, fromanirh commented
/lgtm
/hold
in case @yanirq wants to have another look

2020-12-17 12:16 UTC, yanirq commented
/lgtm

2020-12-17 12:19 UTC, cynepco3hahue commented
/hold cancel

2020-12-17 15:27 UTC, merged

2021-05-13 18:26 UTC, yanirq commented
/cherry-pick release-4.6